CREATE VIEW VW_INVENTORY_ITEM_TEXTINFO
AS SELECT PRTXT.XNM_TEXT_INFO_ID, PRTXT.XNM_OWNER_TABLE_PK , PRTXT.TEXT_LABEL, PRTXT.TEXT_INFO  FROM XNM_TEXT_INFO PRTXT WHERE PRTXT.XNM_OWNER_TABLE_NAME = 'INVENTORY_ITEM'
ORDER BY PRTXT.XNM_OWNER_TABLE_PK ASC, PRTXT.TEXT_LABEL ASC, PRTXT.TEXT_INFO WITH READ ONLY;
