CREATE TABLE XNM_REGISTERED_USER
(
  PROFILE_ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 100 NOT NULL
, CREATED_ON TIMESTAMP DEFAULT SYSTIMESTAMP
, CREATED_BY VARCHAR2(100)
, LAST_MODIFIED_ON TIMESTAMP
, LAST_MODIFIED_BY VARCHAR2(100)
, REGISTERED_ON TIMESTAMP DEFAULT SYSTIMESTAMP
, USER_NAME VARCHAR2(100) NOT NULL
, ACCOUNT_NAME VARCHAR2(200) NOT NULL
, ACCOUNT_STATUS VARCHAR2(20) DEFAULT 'ACTIVE'
, DEFAULT_TIMEZONE VARCHAR2(20)
, CURRENT_COUNTRY VARCHAR(70)
, CURRENT_STATE VARCHAR(70)
, CURRENT_CITY VARCHAR2(70)
, CURRENT_TOWN VARCHAR2(70)
, CONSTRAINT XNM_USER_PROFILE_PK PRIMARY KEY
  (
    PROFILE_ID
  )
  ENABLE
);

COMMENT ON TABLE XNM_REGISTERED_USER IS 'BASIC REGISTERED USER ACCOUNT INFORMATION DETAILS';

COMMENT ON COLUMN XNM_REGISTERED_USER.USER_NAME IS 'USERNAME,LOGIN';

COMMENT ON COLUMN XNM_REGISTERED_USER.ACCOUNT_STATUS IS 'ACTIVE,INACTIVE';

