--liquibase formatted sql
CREATE TABLE liquibase.DATABASECHANGELOG
    (
        "ID" VARCHAR2(255 BYTE) NOT NULL ENABLE,
        "AUTHOR" VARCHAR2(255 BYTE) NOT NULL ENABLE,
        "FILENAME" VARCHAR2(255 BYTE) NOT NULL ENABLE,
        "DATEEXECUTED" TIMESTAMP (6) NOT NULL ENABLE,
        "ORDEREXECUTED" NUMBER(*,0) NOT NULL ENABLE,
        "EXECTYPE" VARCHAR2(10 BYTE) NOT NULL ENABLE,
        "MD5SUM" VARCHAR2(35 BYTE),
        "DESCRIPTION" VARCHAR2(255 BYTE),
        "COMMENTS" VARCHAR2(255 BYTE),
        "TAG" VARCHAR2(255 BYTE),
        "LIQUIBASE" VARCHAR2(20 BYTE),
        "CONTEXTS" VARCHAR2(255 BYTE),
        "LABELS" VARCHAR2(255 BYTE),
        "DEPLOYMENT_ID" VARCHAR2(10 BYTE)
   );

CREATE TABLE liquibase.DATABASECHANGELOGLOCK
    (
        "ID" NUMBER(*,0) NOT NULL ENABLE,
        "LOCKED" NUMBER(1,0) NOT NULL ENABLE,
        "LOCKGRANTED" TIMESTAMP (6),
        "LOCKEDBY" VARCHAR2(255 BYTE),
        CONSTRAINT "PK_DATABASECHANGELOGLOCK" PRIMARY KEY ("ID")
   );

grant insert,update,delete,select on liquibase.DATABASECHANGELOG to XNMPDB_ADMIN;
grant insert,update,delete,select on liquibase.DATABASECHANGELOGLOCK to XNMPDB_ADMIN;