CREATE TABLE XNM_ACCOUNT
(
  XNM_ACCOUNT_ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 100 NOT NULL
, XNM_ACCOUNT_TYPE VARCHAR2(30)
, XNM_ACCOUNT_SERIAL VARCHAR2(100)
, XNM_ACCOUNT_CREATEDTIMESTAMP TIMESTAMP DEFAULT SYSTIMESTAMP
, XNM_ACCOUNT_CREATEDBY VARCHAR2(100)
, XNM_ACCOUNT_LASTUPDATED TIMESTAMP
, XNM_ACCOUNT_LASTUPDATEDBY VARCHAR2(100)
, XNM_ACCOUNT_REGISTERED_ON TIMESTAMP DEFAULT SYSTIMESTAMP
, ACCOUNT_STATUS VARCHAR2(20) DEFAULT 'ACTIVE'
, DEFAULT_TIMEZONE VARCHAR2(20)
, ACCOUNT_COUNTRY VARCHAR2(70)
, ACCOUNT_STATE VARCHAR2(70)
, ACCOUNT_CITY VARCHAR2(70)
, ACCOUNT_TOWN VARCHAR2(70)
, CONSTRAINT XNM_ACCOUNT_PK PRIMARY KEY
  (
    XNM_ACCOUNT_ID
  )
  ENABLE
);

CREATE TABLE XNM_USER
(
  XNM_PROFILE_ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 100 NOT NULL
, XNM_PROFILE_TYPE VARCHAR2(30)
, XNM_PROFILE_DN VARCHAR2(100) NOT NULL
, XNM_PROFILE_FIRSTNAME VARCHAR2(100)
, XNM_PROFILE_MIDDLENAME VARCHAR2(100)
, XNM_PROFILE_LASTNAME VARCHAR2(100)
, XNM_PROFILE_BUSINESSNAME VARCHAR2(100)
, XNM_PROFILE_CREATEDTIMESTAMP TIMESTAMP DEFAULT SYSTIMESTAMP
, XNM_PROFILE_CREATEDBY VARCHAR2(100)
, XNM_PROFILE_LASTUPDATED TIMESTAMP
, XNM_PROFILE_LASTUPDATEDBY VARCHAR2(100)
, XNM_ASSOC_ACCOUNT_ID NUMBER
, XNM_PROFILE_STATUS VARCHAR2(20) DEFAULT 'ACTIVE'
, DEFAULT_TIMEZONE VARCHAR2(20)
, CURRENT_COUNTRY VARCHAR2(70)
, CURRENT_STATE VARCHAR2(70)
, CURRENT_CITY VARCHAR2(70)
, CURRENT_TOWN VARCHAR2(70)
, CONSTRAINT XNM_USER_PROFILE_PK PRIMARY KEY(XNM_PROFILE_ID)ENABLE
);

ALTER TABLE XNM_USER ADD CONSTRAINT XNM_USER_FK_ACCOUNT_ID FOREIGN KEY(XNM_PROFILE_ID) REFERENCES XNM_ACCOUNT(XNM_ACCOUNT_ID) ENABLE;
