./buildOracleXEDockerImage.sh

CMD exec createXnmDBSchemaObjects.sh

RUN $ORACLE_HOME/bin/sqlplus sys/Oracle18@localhost/xnmpdb as sysdba

--connect to xnmpdb as sys

$ORACLE_HOME/bin/sqlplus sys/Oracle18@localhost/xnmpdb as sysdba

@/opt/oracle/scripts/create-xnm-pdb.sql

@/opt/oracle/scripts/update-xnmpdbadmin-account.sql

@/opt/oracle/scripts/db.changelog.initial.sql.create-liquibase-schema.sql