ALTER TABLE XNM_USER ADD CONSTRAINT XNM_USER_FK_ACCOUNT_ID FOREIGN KEY(XNM_PROFILE_ID) REFERENCES XNM_ACCOUNT(XNM_ACCOUNT_ID) ENABLE;
ALTER TABLE XNM_TEXT_INFO ADD CONSTRAINT UN_XNM_TEXT_INFO UNIQUE("XNM_OWNER_TABLE_NAME","XNM_OWNER_TABLE_PK","TEXT_LABEL");
ALTER TABLE XNM_INVENTORY_STORAGE ADD CONSTRAINT FK_XNM_INVENTORYSTORAGE FOREIGN KEY (XNM_INVENTORY_ID) REFERENCES XNM_INVENTORY(XNM_INVENTORY_ID) ENABLE;
ALTER TABLE XNM_ACCOUNT ADD CONSTRAINT UN_ACCOUNT_DOMAIN UNIQUE("PRI_ACCOUNT_DOMAIN");
ALTER TABLE XNM_USER_ACCOUNT_ASSOC ADD CONSTRAINT XNM_ACCOUNTID_FK_XNMACCOUNT FOREIGN KEY(XNM_ACCOUNT_ID) REFERENCES XNM_ACCOUNT(XNM_ACCOUNT_ID) ENABLE;
ALTER TABLE XNM_USER_ACCOUNT_ASSOC ADD CONSTRAINT XNM_PROFILEID_FK_XNMUSER FOREIGN KEY(XNM_PROFILE_ID) REFERENCES XNM_USER(XNM_PROFILE_ID) ENABLE;
ALTER TABLE XNM_USER ADD CONSTRAINT UN_XNMUSER_PROFILE_DN UNIQUE("XNM_PROFILE_DN");
ALTER TABLE XNM_ACCOUNT ADD CONSTRAINT UN_XNMACCOUNT_SERIAL UNIQUE("XNM_ACCOUNT_SERIAL");