./buildOracleXEDockerImage.sh

CMD exec createXnmDBSchemaObjects.sh

RUN $ORACLE_HOME/bin/sqlplus sys/Oracle18@localhost/btcmetrolandpdb as sysdba

--connect to btcmetrolandpdb as sys

$ORACLE_HOME/bin/sqlplus sys/Oracle18@localhost/btcmetrolandpdb as sysdba

@/opt/oracle/scripts/create-btcmetroland-pdb.sql

@/opt/oracle/scripts/update-btcmetrolandpdbadmin-account.sql

@/opt/oracle/scripts/db.changelog.initial.sql.create-liquibase-schema.sql