--SCHEMA WITH LEAST DEPENDENCY <=1 AT THE BOTTOM
DROP TABLE INVENTORY_WAREHOUSE;
DROP TABLE XNM_INVENTORY_STORAGE;
DROP TABLE XNM_INVENTORY;
DROP TABLE XNM_TEXT_INFO;
DROP TABLE XNM_USER_ACCOUNT_ASSOC;
DROP TABLE XNM_USER;
DROP TABLE XNM_ACCOUNT;
