comment on table xnm_inventory is '{catalogue of inventory items [inventory of bags/belts/shoes/herbs]} inventory master header. all text details are stored in xnm_text_info with custom attribute names/values. no explicit foreign keys defined in data model';
comment on column xnm_inventory.inventory_item_id is 'foreign key to inventory_item.inventory_item_id';
comment on column xnm_inventory.inventory_product_id is 'foreign key to inventory_item.inventory_product_id, inherited from inventory_item';
comment on column xnm_inventory.inventory_type is 'enum value [PRODUCT,SERVICE] possibly lookup code?';
comment on column xnm_inventory.service_flag is '[Y/N] compliments the inventory_type column, mutually exclusive to product_flag';
comment on column xnm_inventory.product_flag is '[Y/N] compliments the inventory_type column, mutually exclusive to service_flag';
comment on column xnm_inventory.consumable_flag is '[Y/N] compliments the inventory_type column, disabled and N when service_flag is Y';
comment on column xnm_inventory.inventory_subtype is 'column possibly redundant';
comment on column xnm_inventory.inventory_batch_serial is 'auto generated by service on insert';
comment on column xnm_inventory.inventory_status is '[ACTIVE,DISABLED,ARCHIVED,DELETED]';
comment on column xnm_inventory.XNM_INVENTORY_ACCOUNTPROFILEID is 'xnmuseraccount';
comment on column xnm_inventory.units_added is 'aggregate sum of inventory_stock_level.original_stocklevel for this inventory';
comment on column xnm_inventory.estimated_units_available is 'aggregate sum of inventory_stock_level.estimated_stocklevel_units for this inventory';

comment on table inventory_item is 'inventory item types, can be variations of a product e.g. product = ballpoint pen; inventory item types are [by manufacturer, color, inktype]. This table is a lookup table,  ';
comment on column inventory_item.inventory_item_id is 'primary key';
comment on column inventory_item.product_id is 'foreign key to table product_generic_info';
comment on column inventory_item.inventory_item_status is '[NEW,SUSPENDED,STOPPED....]]';
comment on column inventory_item.itemtype_serialno is 'service generated unique serial number';
comment on column inventory_item.inventory_owner is 'foreign key to xnm_account.xmm_account_id';

comment on table inventory_item_trader is 'traders for an inventory items';
comment on column inventory_item_trader.inventory_item_id is 'foreign key to inventory_item.inventory_item_id';
comment on column inventory_item_trader.trader_profile_id is 'fk to xnmaccount id';
comment on column inventory_item_trader.trade_as is '[TRADER, BROKER]';
comment on column inventory_item_trader.TRADER_REQUEST_UUID is 'trader request uuid serial number maintained by service';
comment on column inventory_item_trader.inventory_id is 'reference to inventory';
comment on column inventory_item_trader.inventory_product_id is 'fk to inventory product';
comment on column inventory_item_trader.INVENTORY_STOCKLEVELBATCH_ID is 'FK TO INVENTORY STOCK BATCH, SHOULD LIMIT TRADER TO JUST THIS BATCH';
comment on column inventory_item_trader.quota_requested is 'total quantity of order units from the associated inventory row a trader has requested for';
comment on column inventory_item_trader.quota_approved is 'total quantity of order units from the associated inventory row a trader has been allocated and max order units that can be sold on behalf of the inventory owner';

comment on table product_generic_info is 'support products on xnm. lookup table of inventory products. [xnm_text_info table stores text attributes]';
comment on column product_generic_info.product_owneraccount_id is 'foreign key to xnm_account.account_id';

comment on table xnm_account is 'trading accounts access control root. every buyer (xnm_user > xnm_trader) will need an association with at least one xnm_account. multiple xnm_users can be linked to one account';
comment on column xnm_account.xnm_account_type is 'INDIVIDUAL, ORGANIZATION';
comment on column xnm_account.xnm_account_serial is 'service generated';
comment on column xnm_account.account_status is 'ACTIVE, DISABLED, INACTIVE, PENDING, NEW';
comment on column xnm_account.default_timezone is 'timezone of individual - sync with xnm_user or organization';
comment on column xnm_account.pri_account_domain is 'primary domain for organization,  will be used by service to prompt domain administrator of new users';

comment on table xnm_inventory_storage is 'storage conditions for each xnm_inventory row.';
comment on column xnm_inventory_storage.xnm_inventory_id is 'foreign key to xnm_inventory which this storage condition describes within a warehouse/place of storage';
comment on column xnm_inventory_storage.storage_type_name is 'name of the storage type, either a standard or custom value';
comment on column xnm_inventory_storage.move_in_date is 'date inventory was moved into this storage type';
comment on column xnm_inventory_storage.move_out_date is 'the date inventory is moved out from this storage type, default value is 31-12-9999.';
comment on column xnm_inventory_storage.move_in_location_id is 'fk to registered physical address id. this can be a verified facility, home address. storage conditions must exist in this location';
comment on column xnm_inventory_storage.expected_store_temp_mx is 'maximum storage temperature';
comment on column xnm_inventory_storage.expected_store_temp_mn is 'minimum storage temperature';
comment on column xnm_inventory_storage.temperature_unit is 'default is [C]entigrade, F';
comment on column xnm_inventory_storage.expected_store_humidity_mx is 'maximum storage humidity';
comment on column xnm_inventory_storage.expected_store_humidity_mn is 'minimum storage humidity';
comment on column xnm_inventory_storage.humidity_units is 'humidity units, default [PERCENT]';
comment on column xnm_inventory_storage.naturallight_flag is 'has natural lights [Y/N]';
comment on column xnm_inventory_storage.organic_store_flag is 'storage unit is organic or ideal for organic products';
comment on column xnm_inventory_storage.perishable_store_flag is 'storage unit is ideal for perishable products';
comment on column xnm_inventory_storage.shelf_life_cal_days is 'maximum days items should be in this storage';
comment on column xnm_inventory_storage.storage_status is 'INUSE,ABN,EXP,FAIL';
comment on column xnm_inventory_storage.storage_verified_by_admin is 'has storage been verified by platform management team';
comment on column xnm_inventory_storage.storage_verified_timestamp is 'date and time storage was verified';
comment on column xnm_inventory_storage.storage_verified_by is 'username of agent who verified storage';
comment on column xnm_inventory_storage.maintained_by is 'xnmaccount serial of business profile responsible for maintaining storage';
comment on column xnm_inventory_storage.STORAGE_UUID is 'record unique serial generated and assigned by service during creation';
comment on column xnm_inventory_storage.WAREHOUSE_ID is 'fk to inventory_warehouse, if not null, then warehouse.addresslocation must be equal to move_in_location_id';

comment on table XNM_PHYSICAL_ADDRESS is 'addresses';
comment on column XNM_PHYSICAL_ADDRESS.xnm_address_line_1 is 'address line 1 mandatory';
comment on column XNM_PHYSICAL_ADDRESS.xnm_address_line_2 is 'address line 2';
comment on column XNM_PHYSICAL_ADDRESS.xnm_address_line_3 is 'address line 3';
comment on column XNM_PHYSICAL_ADDRESS.xnm_address_postcode is 'postcode';
comment on column XNM_PHYSICAL_ADDRESS.address_verified is 'physical verified address is Y, default is N as unverified';
comment on column XNM_PHYSICAL_ADDRESS.NEW_VERSION_ID is 'default is null, when address is modified, a copy is created as new';
comment on column XNM_PHYSICAL_ADDRESS.address_serialno is 'service generated unique serial no for new records. ';
comment on column XNM_PHYSICAL_ADDRESS.PROPERTY_NUMBER is 'E.G 11A';
comment on column XNM_PHYSICAL_ADDRESS.PROPERTY_TYPE is 'E.G HOUSE, BUSINESS, BLOCK';

comment on table BTC_GLOBAL_ADDRESS is 'addresses';
comment on column BTC_GLOBAL_ADDRESS.address_line_1 is 'address line 1 mandatory';
comment on column BTC_GLOBAL_ADDRESS.address_line_2 is 'address line 2';
comment on column BTC_GLOBAL_ADDRESS.address_line_3 is 'address line 3';
comment on column BTC_GLOBAL_ADDRESS.address_postcode is 'postcode';
comment on column BTC_GLOBAL_ADDRESS.address_verified is 'physical verified address is Y, default is N as unverified';
comment on column BTC_GLOBAL_ADDRESS.NEW_VERSION_ID is 'default is null, when address is modified, a copy is created as new';
comment on column BTC_GLOBAL_ADDRESS.address_serialno is 'service generated unique serial no for new records. ';
comment on column BTC_GLOBAL_ADDRESS.PROPERTY_NUMBER is 'E.G 11A';
comment on column BTC_GLOBAL_ADDRESS.PROPERTY_TYPE is 'E.G HOUSE, BUSINESS, BLOCK';

comment on table INVENTORY_WAREHOUSE is 'warehouse details for storing inventories, a warehouse could be an official building or a home or a public facility. text and numeric attributes maintained in xnm_text/numeric_info tables';
comment on column INVENTORY_WAREHOUSE.INVENTORY_WAREHOUSE_ID is 'warehouse id primary key maintained by service';
comment on column INVENTORY_WAREHOUSE.WAREHOUSE_SERIALNO is 'unique warehouse serial number issued by service on create';
comment on column INVENTORY_WAREHOUSE.WAREHOUSE_LOCATION_ADDRESS_ID is 'physical address warehouse is located. fk to btc_global_address';
comment on column INVENTORY_WAREHOUSE.WAREHOUSE_STORAGE_CONDITION_ID is 'fk to storage conditions supported by warehouse';
comment on column INVENTORY_WAREHOUSE.MAINTAINED_BY_XNM_ACCOUNT is 'xnm_account or business responsible for maintaining warehouse';
comment on column INVENTORY_WAREHOUSE.OWNED_BY_XNM_ACCOUNT is 'xnm_account that owns warehouse';
comment on column INVENTORY_WAREHOUSE.PRIMARY_OPERATOR_XNM_ACCOUNT is 'registered primary operator of warehouse';
comment on column INVENTORY_WAREHOUSE.CREATED_ON is 'date record was created';
comment on column INVENTORY_WAREHOUSE.CREATED_BY is 'record created by user';
comment on column INVENTORY_WAREHOUSE.LAST_UPDATED_TIMESTAMP is 'last modified on';
comment on column INVENTORY_WAREHOUSE.LAST_UPDATED_BY is 'last modified by user';
comment on column INVENTORY_WAREHOUSE.WAREHOUSE_STATUS IS 'status [NEW,CLOSED,INUSE]';

comment on table inventory_stock_level is 'volume of units of items in inventory at specified warehouse. an inventory record can have multiple stock level entries (as batches)';
comment on column inventory_stock_level.inventory_stocklevel_id is 'primary key';
comment on column inventory_stock_level.inventory_id is 'fk to inventory associated with stock level';
comment on column inventory_stock_level.stocklevel_uuid is 'service generated unique serial for each stock level/ batch';
comment on column inventory_stock_level.inventory_storage_id is 'fk to storage condition in inventory table';
comment on column inventory_stock_level.inventory_warehouse_id is 'warehouse which inventory is stored';
comment on column inventory_stock_level.original_stocklevel is 'initial number of units of inventory in batch of stock levels.';
comment on column inventory_stock_level.estimated_stocklevel_units is 'estimated current volume of this stock left. to be updated by order service/ events service.';
comment on column inventory_stock_level.last_order_stockunits is 'volume of units in last approved order. must be associated to  last_order_id';
comment on column inventory_stock_level.unit_measure is 'e.g. kgs, volume.. ideally should be the same as that specified for inventorytypes associated product';
comment on column inventory_stock_level.last_order_id is 'id of order last approved. corresponding volume must match last_order_stockunits';
comment on column inventory_stock_level.previous_stocklevel_id is 'last approved order before last_order_id';
comment on column inventory_stock_level.ready_for_trade is 'default is N, orders can only be placed against stock if value is Y';
comment on column inventory_stock_level.all_approved_trader_access is 'default is N, all approved inventory trader have access if value is Y';
comment on column inventory_stock_level.has_curated_trader_list is 'stock has a maintained short list of 1 or more traders who can place order against stock';


comment on table xnm_agreement is 'contractual terms and condition association between xnm partities (accounts, profile)';
comment on column xnm_agreement.agreement_uuid is 'unique serial no maintained by service';
comment on column xnm_agreement.raised_by_account_id is 'xnm account id that initiated agreement';
comment on column xnm_agreement.created_on is 'timestamp record was created';
comment on column xnm_agreement.created_by is 'username of user that created record';
comment on column xnm_agreement.agreement_approved_flag is 'default N, sets to Y when all parties agree to agreement';
comment on column xnm_agreement.agreement_status is 'default DRAFT, changed to SENT when submitted to parties, and INREVIEW when one but not all parties has accepted, DECLINED when any of the parties decline, ACTIVE when all parties accept';
comment on column xnm_agreement.agreement_sent_on is 'date sent to parties';
comment on column xnm_agreement.has_broker_flag is 'default N, Is Y if broker exists in transaction';


comment on table xnm_agreement_parties is 'contractual terms and condition association between xnm partities (accounts, profile)';
comment on column xnm_agreement_parties.agreement_party_uuid is 'unique serial no for agreement';
comment on column xnm_agreement_parties.agreement_id is 'fk to agreement id';
comment on column xnm_agreement_parties.xnm_useraccount_id is 'fk to xnm_account or xnm_user';
comment on column xnm_agreement_parties.xnm_account_type is 'fk to xnm_account';
comment on column xnm_agreement_parties.party_approved_flag is 'default P[ending], A[pproved], D[eclined]';
comment on column xnm_agreement_parties.party_action_status is 'APPROVED, DECLINED';
comment on column xnm_agreement_parties.party_approved_on is 'date agreement approved by party';
comment on column xnm_agreement_parties.party_isbroker_flag is 'party is a broker for the transaction';
