CREATE OR REPLACE PACKAGE BODY "BTC_GLOBAL_ADDRESS_SEARCH" AS
  PROCEDURE CREATE_ADDRESS_SEARCH_ITEM(P_ROWID IN ROWID, P_OUT IN OUT NOCOPY VARCHAR2) IS
  BEGIN
    P_OUT := GET_ADDRESS_SEARCH_ITEM(P_ROWID);
  END CREATE_ADDRESS_SEARCH_ITEM;
  FUNCTION  GET_ADDRESS_ROW_ID(P_ID IN NUMBER) RETURN ROWID IS
  BEGIN
    FOR RR IN (SELECT ROWID FROM BTC_GLOBAL_ADDRESS WHERE ADDRESS_ID = P_ID)
    LOOP
        RETURN RR.ROWID;
    END LOOP;
    RETURN NULL;
  END GET_ADDRESS_ROW_ID;
  FUNCTION  GET_ADDRESS_SEARCH_ITEM(P_ROWID IN ROWID) RETURN VARCHAR2 IS
      BEGIN
        FOR B IN (
            SELECT DISTINCT
                GB.ADDRESS_ID, GB.ADDRESS_SERIALNO, GB.PROPERTY_NUMBER,
                GB.PROPERTY_TYPE, GB.ADDRESS_LINE_1, GB.ADDRESS_LINE_2,
                GB.ADDRESS_LINE_3, GB.ADDRESS_POSTCODE,
                GB.ADDRESS_COUNTRY, GB.ADDRESS_STATE, GB.ADDRESS_CITY,
                GB.ADDRESS_LGA, GB.ADDRESS_COUNCIL, GB.ADDRESS_TOWN,
                GB.ADDRESS_VILLAGE, GB.ADDRESS_VERIFIED
            FROM BTC_GLOBAL_ADDRESS GB
            WHERE GB.ROWID = P_ROWID AND GB.NEW_VERSION_ID IS NULL
        )
        LOOP
            RETURN
            TRIM(
                ''|| CASE WHEN B.PROPERTY_NUMBER IS NOT NULL THEN B.PROPERTY_NUMBER || ' ' ELSE '' END
                  || CASE WHEN B.ADDRESS_LINE_1 IS NOT NULL THEN B.ADDRESS_LINE_1 || ' ' ELSE '' END
                  || CASE WHEN B.ADDRESS_LINE_2 IS NOT NULL THEN B.ADDRESS_LINE_2 || ' ' ELSE '' END
                  || CASE WHEN B.ADDRESS_LINE_3 IS NOT NULL THEN B.ADDRESS_LINE_3 || ' ' ELSE '' END
                  || CASE WHEN B.ADDRESS_POSTCODE IS NOT NULL THEN B.ADDRESS_POSTCODE || ' ' ELSE '' END
                  || CASE WHEN B.ADDRESS_COUNTRY IS NOT NULL THEN B.ADDRESS_COUNTRY || ' ' ELSE '' END
                  || CASE WHEN B.ADDRESS_STATE IS NOT NULL THEN B.ADDRESS_STATE || ' ' ELSE '' END
                  || CASE WHEN B.ADDRESS_CITY IS NOT NULL THEN B.ADDRESS_CITY || ' ' ELSE '' END
                  || CASE WHEN B.ADDRESS_LGA IS NOT NULL THEN B.ADDRESS_LGA || ' ' ELSE '' END
                  || CASE WHEN B.ADDRESS_COUNCIL IS NOT NULL THEN B.ADDRESS_COUNCIL || ' ' ELSE '' END
                  || CASE WHEN B.ADDRESS_TOWN IS NOT NULL THEN B.ADDRESS_TOWN || ' ' ELSE '' END
                  || CASE WHEN B.ADDRESS_VILLAGE IS NOT NULL THEN B.ADDRESS_VILLAGE || ' ' ELSE '' END
                  || CASE WHEN B.ADDRESS_VERIFIED IS NOT NULL THEN B.ADDRESS_VERIFIED ELSE 'N' END);
        END LOOP;
        RAISE NO_DATA_FOUND;
            RETURN NULL;
  END GET_ADDRESS_SEARCH_ITEM;
END BTC_GLOBAL_ADDRESS_SEARCH;