./buildOracleXEDockerImage.sh

CMD exec createDemoDBSchemaObjects.sh

RUN $ORACLE_HOME/bin/sqlplus sys/Oracle18@localhost/liquibasedbpdb as sysdba

--connect to liquibasedbpdb as sys

$ORACLE_HOME/bin/sqlplus sys/Oracle18@localhost/liquibasedbpdb as sysdba

@/opt/oracle/scripts/create-btcmetroland-pdb.sql

@/opt/oracle/scripts/update-liquibasedbpdbadmin-account.sql

@/opt/oracle/scripts/db.changelog.initial.sql.create-liquibase-schema.sql