CREATE TABLE XNM_USER_ACCOUNT_ASSOC
(
    XNM_ASSOCIATION_ID NUMBER,
    XNM_ACCOUNT_ID NUMBER,
    XNM_PROFILE_ID NUMBER,
    XNM_ASSOCATION_STATUS VARCHAR2(30) DEFAULT 'ACTIVE',
    CREATED_TIMESTAMP TIMESTAMP DEFAULT SYSTIMESTAMP,
    CREATED_BY VARCHAR2(200),
    LAST_UPDATEDTIMESTAMP TIMESTAMP,
    LAST_UPDATEDBY VARCHAR2(200),
    CONSTRAINT XNM_ASSOCIATION_PK PRIMARY KEY (XNM_ASSOCIATION_ID) ENABLE
);


ALTER TABLE XNM_USER_ACCOUNT_ASSOC
    ADD CONSTRAINT XNM_ACCOUNTID_FK_XNMACCOUNT
    FOREIGN KEY(XNM_ACCOUNT_ID) REFERENCES XNM_ACCOUNT(XNM_ACCOUNT_ID) ENABLE;

ALTER TABLE XNM_USER_ACCOUNT_ASSOC
    ADD CONSTRAINT XNM_PROFILEID_FK_XNMUSER
    FOREIGN KEY(XNM_PROFILE_ID) REFERENCES XNM_USER(XNM_PROFILE_ID) ENABLE;
