comment on table xnm_inventory is '{catalogue of inventory items [inventory of bags/belts/shoes/herbs]} inventory master header. all text details are stored in xnm_text_info with custom attribute names/values. no explicit foreign keys defined in data model';
comment on column xnm_inventory.inventory_item_id is 'foreign key to inventory_item.inventory_item_id';
comment on column xnm_inventory.inventory_product_id is 'foreign key to inventory_item.inventory_product_id, inherited from inventory_item';
comment on column xnm_inventory.inventory_type is 'enum value [PRODUCT,SERVICE] possibly lookup code?';
comment on column xnm_inventory.service_flag is '[Y/N] compliments the inventory_type column, mutually exclusive to product_flag';
comment on column xnm_inventory.product_flag is '[Y/N] compliments the inventory_type column, mutually exclusive to service_flag';
comment on column xnm_inventory.consumable_flag is '[Y/N] compliments the inventory_type column, disabled and N when service_flag is Y';
comment on column xnm_inventory.inventory_subtype is 'column possibly redundant';
comment on column xnm_inventory.inventory_batch_serial is 'auto generated by service on insert';
comment on column xnm_inventory.inventory_status is '[ACTIVE,DISABLED,ARCHIVED,DELETED]';
comment on column xnm_inventory.XNM_INVENTORY_OWNERPROFILE is 'xnmuseraccount';

comment on table inventory_item is 'inventory item types, can be variations of a product e.g. product = ballpoint pen; inventory item types are [by manufacturer, color, inktype]. This table is a lookup table,  ';
comment on column inventory_item.inventory_item_id is 'primary key';
comment on column inventory_item.product_id is 'foreign key to table product_generic_info';
comment on column inventory_item.inventory_item_status is '[NEW,SUSPENDED,STOPPED....]]';
comment on column inventory_item.itemtype_serialno is 'service generated unique serial number';
comment on column inventory_item.inventory_owner is 'foreign key to xnm_account.xmm_account_id';

comment on table inventory_item_trader is 'traders for an inventory items';
comment on column inventory_item_trader.inventory_item_id is 'foreign key to inventory_item.inventory_item_id';
comment on column inventory_item_trader.trader_profile_id is 'possibly redundant';
comment on column inventory_item_trader.trade_as is ' possibly redundant [TRADER, BROKER]';
comment on column inventory_item_trader.quota is 'total quantity of order units from the associated inventory row a trader has been allocated and max order units that can be sold on behalf of the inventory owner';

comment on table product_generic_info is 'support products on xnm. lookup table of inventory products. [xnm_text_info table stores text attributes]';
comment on column product_generic_info.product_owneraccount_id is 'foreign key to xnm_account.account_id';
