comment on table xnm_inventory is '{catalogue of inventory items [inventory of bags/belts/shoes/herbs]} inventory master header. all text details are stored in xnm_text_info with custom attribute names/values. no explicit foreign keys defined in data model';
comment on column xnm_inventory.inventory_item_id is 'foreign key to inventory_item.inventory_item_id';
comment on column xnm_inventory.inventory_product_id is 'foreign key to inventory_item.inventory_product_id, inherited from inventory_item';
comment on column xnm_inventory.inventory_type is 'enum value [PRODUCT,SERVICE] possibly lookup code?';
comment on column xnm_inventory.service_flag is '[Y/N] compliments the inventory_type column, mutually exclusive to product_flag';
comment on column xnm_inventory.product_flag is '[Y/N] compliments the inventory_type column, mutually exclusive to service_flag';
comment on column xnm_inventory.consumable_flag is '[Y/N] compliments the inventory_type column, disabled and N when service_flag is Y';
comment on column xnm_inventory.inventory_subtype is 'column possibly redundant';
comment on column xnm_inventory.inventory_batch_serial is 'auto generated by service on insert';
comment on column xnm_inventory.inventory_status is '[ACTIVE,DISABLED,ARCHIVED,DELETED]';
comment on column xnm_inventory.XNM_INVENTORY_ACCOUNTPROFILEID is 'xnmuseraccount';

comment on table inventory_item is 'inventory item types, can be variations of a product e.g. product = ballpoint pen; inventory item types are [by manufacturer, color, inktype]. This table is a lookup table,  ';
comment on column inventory_item.inventory_item_id is 'primary key';
comment on column inventory_item.product_id is 'foreign key to table product_generic_info';
comment on column inventory_item.inventory_item_status is '[NEW,SUSPENDED,STOPPED....]]';
comment on column inventory_item.itemtype_serialno is 'service generated unique serial number';
comment on column inventory_item.inventory_owner is 'foreign key to xnm_account.xmm_account_id';

comment on table inventory_item_trader is 'traders for an inventory items';
comment on column inventory_item_trader.inventory_item_id is 'foreign key to inventory_item.inventory_item_id';
comment on column inventory_item_trader.trader_profile_id is 'possibly redundant';
comment on column inventory_item_trader.trade_as is ' possibly redundant [TRADER, BROKER]';
comment on column inventory_item_trader.quota is 'total quantity of order units from the associated inventory row a trader has been allocated and max order units that can be sold on behalf of the inventory owner';

comment on table product_generic_info is 'support products on xnm. lookup table of inventory products. [xnm_text_info table stores text attributes]';
comment on column product_generic_info.product_owneraccount_id is 'foreign key to xnm_account.account_id';


comment on table xnm_account is 'trading accounts access control root. every buyer (xnm_user > xnm_trader) will need an association with at least one xnm_account. multiple xnm_users can be linked to one account';
comment on column xnm_account.xnm_account_type is 'INDIVIDUAL, ORGANIZATION';
comment on column xnm_account.xnm_account_serial is 'service generated';
comment on column xnm_account.account_status is 'ACTIVE, DISABLED, INACTIVE, PENDING, NEW';
comment on column xnm_account.default_timezone is 'timezone of individual - sync with xnm_user or organization';
comment on column xnm_account.pri_account_domain is 'primary domain for organization,  will be used by service to prompt domain administrator of new users';

comment on table xnm_inventory_storage is 'storage conditions for each xnm_inventory row.';
comment on column xnm_inventory_storage.xnm_inventory_id is 'foreign key to xnm_inventory';
comment on column xnm_inventory_storage.storage_type_name is 'name of the storage type, either a standard or custom value';
comment on column xnm_inventory_storage.move_in_date is 'date inventory was moved into this storage type';
comment on column xnm_inventory_storage.move_out_date is 'the date inventory is moved out from this storage type, default value is 31-12-9999.';
comment on column xnm_inventory_storage.move_in_location_id is 'fk to registered inventory warehouse id. this can be a verified facility, home address. storage conditions must exist in this location';
comment on column xnm_inventory_storage.expected_store_temp_mx is 'maximum storage temperature';
comment on column xnm_inventory_storage.expected_store_temp_mn is 'minimum storage temperature';
comment on column xnm_inventory_storage.temperature_unit is 'default is [C]entigrade, F';
comment on column xnm_inventory_storage.expected_store_humidity_mx is 'maximum storage humidity';
comment on column xnm_inventory_storage.expected_store_humidity_mn is 'minimum storage humidity';
comment on column xnm_inventory_storage.humidity_units is 'humidity units, default [PERCENT]';
comment on column xnm_inventory_storage.naturallight_flag is 'has natural lights [Y/N]';
comment on column xnm_inventory_storage.organic_store_flag is 'storage unit is organic or ideal for organic products';
comment on column xnm_inventory_storage.perishable_store_flag is 'storage unit is ideal for perishable products';
comment on column xnm_inventory_storage.shelf_life_cal_days is 'maximum days items should be in this storage';
comment on column xnm_inventory_storage.storage_status is 'INUSE,ABN,EXP,FAIL';
comment on column xnm_inventory_storage.storage_verified_by_admin is 'has storage been verified by platform management team';
comment on column xnm_inventory_storage.storage_verified_timestamp is 'date and time storage was verified';
comment on column xnm_inventory_storage.storage_verified_by is 'username of agent who verified storage';
comment on column xnm_inventory_storage.maintained_by is 'xnmaccount serial of business profile responsible for maintaining storage';
