CREATE TABLE METRO_TEXT_INFO(
  TEXT_INFO_ID NUMBER
, OWNER_TABLE_NAME VARCHAR2(500) NOT NULL
, OWNER_TABLE_PK NUMBER NOT NULL
, TEXT_LABEL VARCHAR2(100) NOT NULL
, TEXT_INFO VARCHAR2(2000)
, CONSTRAINT METRO_TEXT_INFO_PK PRIMARY KEY
  (
    OWNER_TABLE_NAME
  , OWNER_TABLE_PK
  , TEXT_LABEL
  )
  ENABLE
);
