CREATE OR REPLACE PACKAGE "BTC_GLOBAL_ADDRESS_SEARCH" AS
    PROCEDURE CREATE_ADDRESS_SEARCH_ITEM(P_ROWID IN ROWID, P_OUT IN OUT NOCOPY VARCHAR2);
    FUNCTION  GET_ADDRESS_ROW_ID(P_ID IN NUMBER) RETURN ROWID;
    FUNCTION  GET_ADDRESS_SEARCH_ITEM(P_ROWID IN ROWID) RETURN VARCHAR2;
END BTC_GLOBAL_ADDRESS_SEARCH;

/